version: '3.8'  
  
services:  
  frontend:  
    build:  
      context: .  
      dockerfile: Dockerfile.frontend  
    ports:  
      - "3000:80"  
    depends_on:  
      - backend  
    networks:  
      - taskflow-network  
  
  backend:  
    build:  
      context: .  
      dockerfile: Dockerfile.backend  
    ports:  
      - "8000:8000"  
    networks:  
      - taskflow-network  
  
networks:  
  taskflow-network:  
    driver: bridge
